// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr6FqxgGBvbkUdpVdYyYHtnUrxoZVJ6qU',
    appId: '1:811825873975:web:72f673c9ce4fece9e8ebb2',
    messagingSenderId: '811825873975',
    projectId: 'botanicapp-74dee',
    authDomain: 'botanicapp-74dee.firebaseapp.com',
    storageBucket: 'botanicapp-74dee.appspot.com',
    measurementId: 'G-X0L26LB4D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGz0SdNozsa1YtWzqSSNC6uAcaUUKMh6Y',
    appId: '1:811825873975:android:d5daffebd68e748ae8ebb2',
    messagingSenderId: '811825873975',
    projectId: 'botanicapp-74dee',
    storageBucket: 'botanicapp-74dee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0DVKCOYJEUEcysysrMa8h8XTkgYxvZ7M',
    appId: '1:811825873975:ios:e9f4e19c9dbe058ce8ebb2',
    messagingSenderId: '811825873975',
    projectId: 'botanicapp-74dee',
    storageBucket: 'botanicapp-74dee.appspot.com',
    iosClientId: '811825873975-pqj6rkkcm80aim4l0p0nminu1mf4ovc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0DVKCOYJEUEcysysrMa8h8XTkgYxvZ7M',
    appId: '1:811825873975:ios:e9f4e19c9dbe058ce8ebb2',
    messagingSenderId: '811825873975',
    projectId: 'botanicapp-74dee',
    storageBucket: 'botanicapp-74dee.appspot.com',
    iosClientId: '811825873975-pqj6rkkcm80aim4l0p0nminu1mf4ovc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr6FqxgGBvbkUdpVdYyYHtnUrxoZVJ6qU',
    appId: '1:811825873975:web:dc2079cd3e07ef0be8ebb2',
    messagingSenderId: '811825873975',
    projectId: 'botanicapp-74dee',
    authDomain: 'botanicapp-74dee.firebaseapp.com',
    storageBucket: 'botanicapp-74dee.appspot.com',
    measurementId: 'G-7D3JHWEBM1',
  );
}
